# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselleedetails',
            name='phoneNo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='counselleedetails',
            name='uid',
            field=models.CharField(max_length=20),
        ),
    ]
