# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellee', '0002_auto_20170327_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselleedetails',
            name='phoneNo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='counselleedetails',
            name='uid',
            field=models.BigIntegerField(),
        ),
    ]
