# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellee', '0004_counselleedetails_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselleedetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='counselleedetails',
            name='problem',
        ),
    ]
