# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_remove_allusers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselleesessions',
            name='username',
        ),
        migrations.RemoveField(
            model_name='counsellorsessions',
            name='username',
        ),
        migrations.DeleteModel(
            name='CounselleeSessions',
        ),
        migrations.DeleteModel(
            name='CounsellorSessions',
        ),
    ]
