# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Counsellee', '0005_auto_20170330_0021'),
        ('Counsellor', '0003_auto_20170329_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('requestedDate', models.DateField()),
                ('requestedTime', models.TimeField()),
                ('problem', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('reports', models.TextField()),
                ('counselleeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellee.CounselleeDetails')),
                ('counsellorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellor.CounsellorDetails')),
            ],
        ),
    ]
