# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('uid', models.BigIntegerField()),
                ('phoneNo', models.BigIntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('speciality', models.CharField(max_length=100)),
                ('role', models.CharField(default='Counsellor', max_length=10)),
                ('isIdle', models.BooleanField(default=True)),
                ('noOfSessions', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
