# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emailID', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('specialisation', models.CharField(max_length=50)),
                ('uid', models.BigIntegerField()),
            ],
        ),
    ]
