# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellordetails',
            name='role',
            field=models.CharField(default='Counsellor', max_length=10),
        ),
    ]
