# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0002_counsellordetails_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellordetails',
            name='isidle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellordetails',
            name='noOfSessions',
            field=models.IntegerField(default=0),
        ),
    ]
