# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0003_auto_20170329_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellordetails',
            name='nextCounsellingDate',
            field=models.DateField(default=None),
        ),
    ]
